# Generated by Django 4.1.2 on 2022-12-10 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio_class',
            name='curr_size',
        ),
        migrations.AddField(
            model_name='studio_class',
            name='start_Date',
            field=models.DateField(default=datetime.date(2022, 12, 10)),
            preserve_default=False,
        ),
    ]
