# Generated by Django 4.1.2 on 2022-12-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studios', '0002_remove_studio_class_curr_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_instance',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
